[package]
name = "kmbox-ai-rust"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
bindgen = "0.72.0"

[lib]
name = "kmbox_ai_rust"
crate-type = ["cdylib", "rlib"]

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
